#!/bin/sh
# Removes the xhispertoold symlink created by postinst - dpkg only tracks
# files it installed directly, not this manually-created symlink.
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /usr/bin/xhispertoold
fi

exit 0
