#!/bin/sh
# $1 == 0 means this is the final removal (not an upgrade) - only then
# should the manually-created xhispertoold symlink be removed.
if [ "$1" = "0" ]; then
    rm -f /usr/bin/xhispertoold
fi

exit 0
